<?php

declare(strict_types=1);

namespace PHPAML\Api;

final class TypeScriptClientGenerator
{
    /** @param array<string, mixed> $document */
    public function generate(array $document): string
    {
        $methods = [];
        foreach (($document['paths'] ?? []) as $path => $operations) {
            if (!is_array($operations)) {
                continue;
            }
            foreach ($operations as $verb => $operation) {
                if (!is_array($operation)) {
                    continue;
                }
                $name = $this->identifier((string) ($operation['operationId'] ?? $verb . $path));
                preg_match_all('/\{([A-Za-z_][A-Za-z0-9_]*)\}/', (string) $path, $matches);
                $params = array_map(static fn (string $param): string => $param . ': string | number', $matches[1] ?? []);
                $hasBody = in_array(strtolower((string) $verb), ['post', 'put', 'patch'], true);
                if ($hasBody) {
                    $params[] = 'body: unknown';
                }
                $url = preg_replace_callback('/\{([^}]+)\}/', static fn (array $match): string => '${encodeURIComponent(String(' . $match[1] . '))}', (string) $path);
                $options = "{ method: '" . strtoupper((string) $verb) . "'" . ($hasBody ? ', body: JSON.stringify(body)' : '') . ' }';
                $methods[] = "  {$name}(" . implode(', ', $params) . "): Promise<unknown> {\n    return this.request(`{$url}`, {$options});\n  }";
            }
        }
        return "// Generated by PHPAML. Do not edit manually.\n"
            . "export class PhpamlApiClient {\n"
            . "  constructor(private baseUrl: string, private token?: string) {}\n\n"
            . "  private async request(path: string, init: RequestInit): Promise<unknown> {\n"
            . "    const headers: Record<string, string> = { Accept: 'application/json', 'Content-Type': 'application/json' };\n"
            . "    if (this.token) headers.Authorization = `Bearer \${this.token}`;\n"
            . "    const response = await fetch(this.baseUrl.replace(/\\\/$/, '') + path, { ...init, headers });\n"
            . "    const payload = response.status === 204 ? undefined : await response.json();\n"
            . "    if (!response.ok) throw payload;\n"
            . "    return payload;\n  }\n\n"
            . implode("\n\n", $methods) . "\n}\n";
    }

    private function identifier(string $value): string
    {
        $value = lcfirst(str_replace(' ', '', ucwords((string) preg_replace('/[^A-Za-z0-9]+/', ' ', $value))));
        return preg_match('/^[A-Za-z_$]/', $value) ? $value : 'call' . ucfirst($value);
    }
}
